# -*- coding: utf-8 -*-
"""EdgeDetection

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EfMVt8TPa4plU-Tlhii2E1Ym3Buj_lAF
"""

import numpy as np
import random

array2 = np.zeros(36)
for i in range (36):
  array2[i] = int((random.randint(0,9)))

# let, reshape into 6*6 size array
m = 6

array2 = array2.reshape (m,m)
array2

kernel = [
          [1,0,-1],
          [1,0,-1],
          [1,0,-1]
]

result = np.zeros(16)
result = result.reshape(4,4)


for i in range (0,4): # for every row
  for j in range(0,4):  # for every column
    
    #building the tempbox
    tempbox = []
    for k in range(i,i+3):  # for every row in filtered box
      for l in range(j,j+3):  # for every col in filtered box
        tempbox.append(array2[k][l])
    tempbox = np.asarray(tempbox)
    tempbox = tempbox.reshape(3,3)
    #processing the tempbox
    np.multiply (tempbox, kernel)
    tempsum = np.sum(tempbox)
    result[i][j] = tempsum

print(result)